export const AIR_PURIFIERS = {
  'zhimi.airpurifier.v5': 'Air Purifier V5',
  'zhimi.airpurifier.v6': 'Air Purifier Pro',
  'zhimi.airpurifier.v7': 'Air Purifier Pro V7',
  'zhimi.airpurifier.m1': 'Air Purifier 2 (mini)',
  'zhimi.airpurifier.m2': 'Air Purifier (mini)',
  'zhimi.airpurifier.ma1': 'Air Purifier MA1',
  'zhimi.airpurifier.ma2': 'Air Purifier MA2',
  'zhimi.airpurifier.mc1': 'Air Purifier 2S',
  'zhimi.airpurifier.mc2': 'Air Purifier 2H',
  'zhimi.airpurifier.sa1': 'Air Purifier Super',
  'zhimi.airpurifier.sa2': 'Air Purifier Super 2',
  'zhimi.airpurifier.mb3': 'Air Purifier 3H',
  'zhimi.airpurifier.ma4': 'Air Purifier 3',
  'zhimi.airpurifier.za1': 'Air Purifier ZA1',
};
